question_data = [
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Linus Torvalds created Linux and Git.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The logo for Snapchat is a Bell.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "RAM stands for Random Access Memory.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Ada Lovelace is often considered the first computer programmer.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                       "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                      "question": "The Windows 7 operating system has six main editions.",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The Windows ME operating system was released in the year 2000.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                       "question": "Linux was first created as an alternative to Windows XP.",
                                       "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "The music group Daft Punk got their name from a negative review they recieved.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "American rapper Dr. Dre actually has a Ph.D. doctorate.", "correct_answer": "False",
     "incorrect_answers": ["True"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                      "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
                                      "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "The song &quot;Stronger Than You&quot; is a single by Estelle, who played Garnet in Steven Universe.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "A Saxophone is a brass instrument.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "Daft Punk originated in France.", "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "Stevie Wonder&#039;s real name is Stevland Hardaway Morris.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                       "question": "Scatman John&#039;s real name was John Paul Larkin.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "John Williams composed the music for &quot;Star Wars&quot;.", "correct_answer": "True",
     "incorrect_answers": ["False"]}, {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                                       "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
                                       "correct_answer": "True", "incorrect_answers": ["False"]}]
